frequency: 30.0
sensor_timeout: 0.1
two_d_mode: true

publish_acceleration: false

map_frame: map          # 未来の拡張用。今は world_frame=odom なので map→odom TF は出ない
odom_frame: odom
base_link_frame: base_link
world_frame: odom

odom0: /wheel_odom

# 15 要素: x y z roll pitch yaw vx vy vz vroll vpitch vyaw ax ay az
odom0_config: [true, true, false,
               false, false, true,
               true, true, false,
               false, false, true,
               false, false, false]

odom0_differential: false
odom0_relative: false

# 状態遷移ノイズ（必要に応じ調整）
process_noise_covariance:
  [0.05, 0,    0,    0,    0,    0,
   0,    0.05, 0,    0,    0,    0,
   0,    0,    0.0,  0,    0,    0,
   0,    0,    0,    0.0,  0,    0,
   0,    0,    0,    0,    0.0,  0,
   0,    0,    0,    0,    0,    0.05]

initial_estimate_covariance:
  [1.0, 0,   0,   0,   0,   0,
   0,   1.0, 0,   0,   0,   0,
   0,   0,   0.0, 0,   0,   0,
   0,   0,   0,   0.0, 0,   0,
   0,   0,   0,   0,   0.0, 0,
   0,   0,   0,   0,   0,   1.0]