ekf_odom:
  ros__parameters:
    frequency: 20.0
    sensor_timeout: 0.3
    two_d_mode: true  # 2D 平面前提モード
    publish_acceleration: false # 加速度は publish しない

    map_frame: map
    odom_frame: odom
    base_link_frame: base_link
    world_frame: odom

    # Wheel odometry
    odom0: wheel_odom
    # 15 個の bool は、robot_localization が扱う状態ベクトル (順番固定) のどの要素をこのセンサメッセージから利用するかを指定するマスク
    # [x,y,z, roll,pitch,yaw,  vx,  vy,  vz,  vroll, vpitch, vyaw,  ax, ay, az]
    odom0_config: [false, false, false, false, false, false, true, true, false, false, false, true, false, false, false]
    odom0_differential: false #true にすると、そのセンサが与える pose を差分（前回との差分＝速度的情報）として扱うモード。wheel odom は既に速度も含んでいるので通常 false
    odom0_relative: false # true にするとセンサの pose は初回値からの相対変化として扱われる（センサ自身が jump する可能性がある場合の手当て）。
    odom0_queue_size: 5
    odom0_nodelay: false
    odom0_pose_rejection_threshold: 5.0    # [m / rad] 相当（Poseの大外れカット）
    odom0_twist_rejection_threshold: 1.5   # [m/s / rad/s] の大外れカット
    # デバッグしたいとき:
    print_diagnostics: true