ekf_node:
  ros__parameters:
    two_d_mode: true
    world_frame: odom
    odom_frame: odom
    base_link_frame: base_footprint

    odom0: /odom
    odom0_config: [true,  true,  false,
                   false, false, false,
                   true,  true,  false,
                   false, false, true,
                   false, false, false]
    odom0_differential: false
    odom0_relative: false

    imu0: /imu/data
    imu0_config: [false, false, false,
                  true,  true,  true,
                  false, false, false,
                  true,  true,  true,
                  true,  true,  true]