# Input topics handled/muxed.
# For each topic:
# - name    : name identifier to select the topic (*sub-namespace, see below)
# - topic   : input topic of geometry_msgs::Twist type
# - timeout : timeout in seconds to start discarding old messages, and use 0.0 speed instead
# - priority: priority in the range [0, 255]; the higher the more priority over other topics

twist_mux:
  ros__parameters:
    topics:
      keyboard:
        topic   : key_vel
        timeout : 0.5
        priority: 250
      joystick:
        topic   : joy_vel
        timeout : 0.5
        priority: 240
      remote_keyboard: # Control commands sent from Makuhari Messe
        topic   : /remote/key_vel
        timeout : 0.5
        priority: 150
      remote_joystick: # Control commands sent from Makuhari Messe
        topic   : /remote/joy_vel
        timeout : 0.5
        priority: 140
      remote_tatto: # Control commands sent from Makuhari Messe
        topic   : /remote/tatto_vel
        timeout : 0.5
        priority: 130
      navigation:
        topic   : nav_vel
        timeout : 0.5
        priority: 50

    locks:
      reject_from_remote: # Rejecting cmd_vel input from Makuhari
        topic   : reject_makuhari_vel
        timeout : 0.0
        priority: 200
      reject_tatto_vel :
        topic   : reject_tatto_vel
        timeout : 0.0
        priority: 135