velocity_smoother:
  ros__parameters:
    smoothing_frequency: 50.0
    feedback: "OPEN_LOOP"
    odom_topic: "/odom"

    max_velocity:
      linear_x: 0.30
      linear_y: 0.30
      angular_z: 0.40
    min_velocity:
      linear_x: -0.30
      linear_y: -0.30
      angular_z: -0.40

    max_accel:
      linear_x: 0.50
      linear_y: 0.50
      angular_z: 0.70
    max_decel:
      linear_x: -0.60
      linear_y: -0.60
      angular_z: -0.80

    velocity_timeout: 0.4
    raw_cmd_vel_topic: "/cmd_vel_raw"
    smoothed_cmd_vel_topic: "/cmd_vel"